name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate dark snake SVG only
        uses: Platane/snk@v3
        with:    
          github_user_name: lohaniprateek
          outputs: dist/github-contribution-grid-snake-dark.svg
          palette: |
            background: "#000000"
            snake: "#39FF14"
            apple: "#ff073a"
            head: "#00ffcc"
            color_0: "#161b22"
            color_1: "#0d1117"
            color_2: "#21262d"
            color_3: "#30363d"
            color_4: "#58a6ff"

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
